CS4790ME/Controllers/ServiceEventController.cs
using System.Net;
using System.Web.Mvc;
using CS4790ME.Models;

namespace CS4790ME.Controllers
{
    public class ServiceEventController : Controller
    {
        private BasicVehicleDbContext db = new BasicVehicleDbContext();

        // GET: ServiceEvent
        public ActionResult Index()
        {
            return View(Repository.getServiceEvents());
        }

        // GET: ServiceEvent/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceEvent serviceEvent = Repository.getServiceEvent(id);
            if (serviceEvent == null)
            {
                return HttpNotFound();
            }
            return View(serviceEvent);
        }

        // GET: ServiceEvent/Create
        public ActionResult Create(string vin)

        {
            ServiceEvent myServiceEvent = new ServiceEvent();
            myServiceEvent.Vin = vin;
            return View(myServiceEvent);
        }

        // POST: ServiceEvent/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ServiceDate,Vin,ServiceType,ServiceMileage,ServiceAmount")] ServiceEvent serviceEvent, string vin)
        {
            if (ModelState.IsValid)
            {
                serviceEvent.Vin = vin;
                Repository.createServiceEvent(serviceEvent);
                return RedirectToAction("Index");
            }

            return View(serviceEvent);
        }

        // GET: ServiceEvent/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceEvent serviceEvent = Repository.getServiceEvent(id);
            if (serviceEvent == null)
            {
                return HttpNotFound();
            }
            return View(serviceEvent);
        }

        // POST: ServiceEvent/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ServiceDate,Vin,ServiceType,ServiceMileage,ServiceAmount")] ServiceEvent serviceEvent)
        {
            if (ModelState.IsValid)
            {
                Repository.editServiceEvent(serviceEvent);
                return RedirectToAction("Index");
            }
            return View(serviceEvent);
        }

        // GET: ServiceEvent/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServiceEvent serviceEvent = Repository.getServiceEvent(id);
            if (serviceEvent == null)
            {
                return HttpNotFound();
            }
            return View(serviceEvent);
        }

        // POST: ServiceEvent/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ServiceEvent serviceEvent = Repository.getServiceEvent(id);
            Repository.deleteServiceEvent(serviceEvent);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CS4790ME/Controllers/VehicleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CS4790ME.Models;

namespace CS4790ME.Controllers
{
    public class VehicleController : Controller
    {
        private BasicVehicleDbContext db = new BasicVehicleDbContext();

        // GET: Vehicle
        public ActionResult Index()
        {
            return View();
        }

        // GET: Vehicle/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VehicleServiceEvent vehServiceEvent = Repository.getVehicleAndServiceEvents(id);
            if (vehServiceEvent == null)
            {
                return HttpNotFound();
            }
            return View(vehServiceEvent);
        }

        // GET: Vehicle/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vehicle/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Vin,Make,Model,Year,CurrentMileage")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                Repository.createVehicle(vehicle);

                return RedirectToAction("Index");
            }

            return View(vehicle);
        }

        // GET: Vehicle/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = Repository.getVehicle(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // POST: Vehicle/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Vin,Make,Model,Year,CurrentMileage")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
                Repository.editVehicle(vehicle);
                return RedirectToAction("Index");
            }
            return View(vehicle);
        }

        // GET: Vehicle/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehicle vehicle = Repository.getVehicle(id);
            if (vehicle == null)
            {
                return HttpNotFound();
            }
            return View(vehicle);
        }

        // POST: Vehicle/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vehicle vehicle = Repository.getVehicle(id);
            Repository.deleteVehicle(vehicle);

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CS4790ME/Views/Vehicle/Create.cshtml
@model CS4790ME.Models.Vehicle

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vehicle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Vin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Make, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Make, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Make, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurrentMileage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurrentMileage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CurrentMileage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CS4790ME/Views/Vehicle/Delete.cshtml
@model CS4790ME.Models.Vehicle

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vehicle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Vin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Make)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Make)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrentMileage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrentMileage)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CS4790ME/Views/Vehicle/Details.cshtml
@model CS4790ME.Models.VehicleServiceEvent

@{
    ViewBag.Title = "Vehicle Details";
}

<h2>Vehicle Details</h2>

<div>
    <h4>Vehicle Info</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.vehicle.Vin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vehicle.Vin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vehicle.Make)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vehicle.Make)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vehicle.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vehicle.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vehicle.Year)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vehicle.Year)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.vehicle.CurrentMileage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.vehicle.CurrentMileage)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.vehicle.Id })
</p>

<h4>Service History</h4>
<p>
    @Html.ActionLink("New Service Event", "Create", "ServiceEvent", new { vin = Model.vehicle.Vin }, null)
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.serviceEvents[0].ServiceDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.serviceEvents[0].Vin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.serviceEvents[0].ServiceType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.serviceEvents[0].ServiceMileage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.serviceEvents[0].ServiceAmount)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.serviceEvents)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ServiceDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ServiceType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ServiceMileage)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ServiceAmount)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>
<p>
    @Html.ActionLink("Back to Vehicles", "Index", "Vehicle")
</p>

CS4790ME/Views/Vehicle/Edit.cshtml
@model CS4790ME.Models.Vehicle

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vehicle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Vin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Make, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Make, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Make, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurrentMileage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurrentMileage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CurrentMileage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CS4790ME/Views/Vehicle/Index.cshtml
@model IEnumerable<Vehicle>
@using CS4790ME.Models
@using MVCGrid.Web
@{
    ViewBag.Title = "Index";
}


<div class="center-block">
    <h2>60Hz Input History</h2>
</div>

<div class="panel panel-default">
    <div class="panel-body">
        @Html.Partial("_MVCGridToolbar", new MVCGridToolbarModel()
   {
       MVCGridName = "Vehicles",
       PageSize = true,
       ColumnVisibility = true,
       Export = true,
       GlobalSearch = true
   })
        @Html.MVCGrid("Vehicles")
    </div>
</div>